#[cfg(feature = "affine")]
pub mod affine;
#[cfg(feature = "atbash")]
pub mod atbash;
#[cfg(feature = "bacon")]
pub mod bacon;
#[cfg(feature = "caesar")]
pub mod caesar;
#[cfg(feature = "polybius_square")]
pub mod polybius_square;
#[cfg(feature = "rot")]
pub mod rot;
#[cfg(feature = "scytale")]
pub mod scytale;
#[cfg(feature = "vigenere")]
pub mod vigenere;
#[cfg(feature = "xor")]
pub mod xor;
